---
- hosts: switches
  gather_facts: 'no'
  # Run Anisble on the local server using CLI or eAPI to the node
  connection: local
  vars:
    model_name: '{{ version_data.stdout[0].modelName }}'
    eos_version: '{{ version_data.stdout[0].internalVersion }}'

  tasks:
    - name: Get Version
      eos_command:
        commands='show version'
        provider={{ eos_connection }}
      register: version_data

    - debug: msg='{{ version_data }}'

    - name: Print report
      template:
        src: version_report.j2
        dest: ./version_report-{{ inventory_hostname }}.txt

    - name: Configure vlans
      eos_config:
        src: vlans.j2
        provider: "{{ eos_connection }}"
