---
- hosts: switches
  gather_facts: 'no'
  # Run Anisble on the local server using CLI or eAPI to the node
  connection: local
  vars:
    eapi_conn:
      host: '{{ inventory_hostname }}'
      username: admin
      password: 
      transport: eapi
      use_ssl: true
      validate_certs: false
  tasks:
    - name: Get version
      eos_command:
        commands='show version'
        provider={{ eapi_conn }}
